name: seshly
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # ----------------------------
  # UI / ICONS
  # ----------------------------
  cupertino_icons: ^1.0.8

  # ----------------------------
  # FIREBASE CORE
  # ----------------------------
  firebase_core: ^2.27.0

  # ----------------------------
  # AUTHENTICATION
  # ----------------------------
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.1 # optional, future social login

  # ----------------------------
  # DATABASE
  # ----------------------------
  cloud_firestore: ^4.15.0

  # ----------------------------
  # ANALYTICS / GROWTH (FUTURE)
  # ----------------------------
  firebase_analytics: ^10.8.0

  # ----------------------------
  # STORAGE (FUTURE: PROFILE PICS, NOTES)
  # ----------------------------
  firebase_storage: ^11.6.0

  # ----------------------------
  # NOTIFICATIONS (FUTURE)
  # ----------------------------
  firebase_messaging: ^14.7.10

  # ----------------------------
  # STATE MANAGEMENT (LIKELY)
  # ----------------------------
  provider: ^6.1.2

  # ----------------------------
  # UTILITIES
  # ----------------------------
  intl: ^0.19.0        # date / time formatting
  uuid: ^4.4.0        # ids for sessions, notes, etc
  flutter_speed_dial: ^7.0.0
  image_picker: ^1.0.0
  video_player: ^2.8.1
  url_launcher: ^6.2.1
  share_plus: ^7.2.2
  path_provider: ^2.1.1
  image_gallery_saver: ^2.0.3
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  file_picker: ^8.0.0
  crypto: ^3.0.3
  syncfusion_flutter_pdf: ^26.2.14
  syncfusion_flutter_pdfviewer: ^26.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/seshly_logo_colored.svg
    - assets/images/seshly_logo_white.svg
    - assets/images/seshly_logo_full.svg
